#!/usr/bin/env bash

# dependencies: dunst scrot

screenie() {
	scrot /home/anzu/usr/png/screenshots/ss_$(date "+%d%m%y-%h%m").png; \
	dunstify -r 4 "screenshot taken"
}

echo -n "say cheese"

for i in {1..3}
do
	echo -n " $i"
	sleep 0.5
done

echo

screenie
